Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                     count    min threads    max threads
--------------------  -------  -------------  -------------
GatherFASTAs                1              1              1
OFOG_Representatives        1              1              1
Setup                       1              1              1
all                         1              1              1
download_UP                 1              1              1
gunzip_UP                   2              1              1
orthofinder                 1              4              4
total                       8              1              4

Select jobs to execute...

[Tue May 28 13:08:15 2024]
rule Setup:
    output: Data/output/AssemblyQC.png, Data/input/UPID_OOI.txt, Data/input/TaxonID.txt
    jobid: 5
    reason: Missing output files: Data/output/AssemblyQC.png
    resources: tmpdir=/var/folders/qr/vm827mh53sd6708z2k3_tnnrz3fj08/T

[Tue May 28 13:08:15 2024]
rule download_UP:
    output: Data/input/Proteomes/UP000321408.fasta.gz, Data/input/Proteomes/UP000324665.fasta.gz
    jobid: 2
    reason: Missing output files: Data/input/Proteomes/UP000324665.fasta.gz, Data/input/Proteomes/UP000321408.fasta.gz
    resources: tmpdir=/var/folders/qr/vm827mh53sd6708z2k3_tnnrz3fj08/T

[Tue May 28 13:08:15 2024]
Error in rule Setup:
    jobid: 5
    output: Data/output/AssemblyQC.png, Data/input/UPID_OOI.txt, Data/input/TaxonID.txt

RuleException:
WorkflowError in line 33 of /Users/phivri/Documents/Github/Biosustain/Methylotrophy/Snakefile:
Failed to open source file /Users/phivri/Documents/Github/Biosustain/Methylotrophy/python Scripts/Setup.py 1935183
FileNotFoundError: [Errno 2] No such file or directory: '/Users/phivri/Documents/Github/Biosustain/Methylotrophy/python Scripts/Setup.py 1935183'
  File "/Users/phivri/Documents/Github/Biosustain/Methylotrophy/Snakefile", line 33, in __rule_Setup
  File "/Users/phivri/Applications/mambaforge/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 58, in run
[Tue May 28 13:08:18 2024]
Finished job 2.
1 of 8 steps (12%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-05-28T130805.215159.snakemake.log
